spring:
  data:
    mongodb:
      database: transactions
      uri: mongodb://root:rootpassword@localhost:27017/?retryWrites=true&w=1&j=false
      auto-index-creation: true
      username: root
      password: rootpassword

server:
  port: 3000
